### ISSUE TITLE
Got this error when ran at bart4

### ISSUE THREAD

**Issue by rizar** [mila-udem/platoon#28] opened 2016-01-15 15:58 UTC
Traceback (most recent call last):
  File "/u/bahdanau/Dist/blocks-examples/mnist/__init__.py", line 144, in <module>
    args.learning_rate, args.sync_freq, args.rule, args.alpha)
  File "/u/bahdanau/Dist/blocks-examples/mnist/__init__.py", line 121, in main
    main_loop.run()
  File "/u/bahdanau/Dist/blocks/blocks/main_loop.py", line 197, in run
    reraise_as(e)
  File "/u/bahdanau/Dist/blocks/blocks/utils/__init__.py", line 228, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "/u/bahdanau/Dist/blocks/blocks/main_loop.py", line 170, in run
    self._run_extensions('before_training')
  File "/u/bahdanau/Dist/blocks/blocks/main_loop.py", line 263, in _run_extensions
    extension.dispatch(CallbackName(method_name), *args)
  File "/u/bahdanau/Dist/blocks/blocks/extensions/__init__.py", line 338, in dispatch
    self.do(callback_invoked, *(from_main_loop + tuple(arguments)))
  File "/u/bahdanau/Dist/blocks-extras/blocks_extras/extensions/synchronization.py", line 26, in do
    self.worker.init_shared_params(self.main_loop.model.parameters)
  File "/u/bahdanau/Dist/blocks-extras/blocks_extras/extensions/synchronization.py", line 50, in init_shared_params
    self.job_name, parameters, self.sync_rule)
  File "/u/bahdanau/Dist/platoon/platoon/channel.py", line 297, in init_shared_params
    self._shmref = posix_ipc.SharedMemory(job_name+'params')
posix_ipc.ExistentialError: No shared memory exists with the specified name

**Comment by mgermain** [comment] 2016-01-15 16:23
My guess would be that this is caused by a worker, which is not the main one, that tries to use the share_memory before it's initialized.

I'll have a PR in a couple hours that should remove the need to specify explicitly a "main" worker and take care of that kind of timing problem.

**Comment by mgermain** [comment] 2016-01-15 21:21
PR #29 merged, let me know if this fixes it.

**Closed** 2016-02-01 23:24 UTC
Labels: bug
