### ISSUE TITLE
error occurred when installed gpuarray

### ISSUE THREAD

**Issue by kobecsb** [mila-udem/platoon#86] opened 2017-02-13 05:58 UTC
Hi, I was using anaconda2 to install theano and platoon. 
When I installed libgpuarray and pygpu successfully, and then tried to run the example 'lstm', the error occurs as following (anyone could help please?):

```
Traceback (most recent call last):
  File "/search/odin/chengshanbo/anaconda2/bin/platoon-launcher", line 4, in <module>
    __import__('pkg_resources').run_script('platoon==0.6.1', 'platoon-launcher')
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/search/odin/chengshanbo/.local/lib/python2.7/site-packages/platoon-0.6.1-py2.7.egg/EGG-INFO/scripts/platoon-launcher", line 31, in <module>
    
  File "build/bdist.linux-x86_64/egg/platoon/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/platoon/channel/__init__.py", line 14, in <module>
  File "build/bdist.linux-x86_64/egg/platoon/channel/worker.py", line 46, in <module>
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/__init__.py", line 32, in <module>
    from . import fft, dnn, opt, nerv, extra_ops, multinomial, reduction
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/fft.py", line 14, in <module>
    from .opt import register_opt, op_lifter, register_opt2
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/opt.py", line 57, in <module>
    from .blocksparse import (GpuSparseBlockGemv, GpuSparseBlockOuter,
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blocksparse.py", line 91, in <module>
    gpu_sparse_block_gemv = GpuSparseBlockGemv(False)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blocksparse.py", line 31, in __init__
    COp.__init__(self, "blockgemv.c", "APPLY_SPECIFIC(blockgemv)")
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 1277, in __init__
    self.load_c_code(func_files)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 1357, in load_c_code
    "%s" % func_files[i])
ValueError: No valid section marker was found in file /search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blockgemv.c

```

**Comment by kobecsb** [comment] 2017-02-13 09:41
And, it seems not be caused by gpuarray.
Such error occurs when
```
import platoon
```

**Comment by kobecsb** [comment] 2017-02-13 09:44
It happens immediately when import platoon. I installed platoon by cloning it to local dir, and 
```
python setup.py install
```
Another cleaner error info is like:
```
>>> import platoon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/search/odin/chengshanbo/platoon/platoon/__init__.py", line 2, in <module>
    from .channel.controller import Controller
  File "/search/odin/chengshanbo/platoon/platoon/channel/__init__.py", line 14, in <module>
    from .worker import Worker
  File "/search/odin/chengshanbo/platoon/platoon/channel/worker.py", line 46, in <module>
    from theano import gpuarray as theanoga
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/__init__.py", line 32, in <module>
    from . import fft, dnn, opt, nerv, extra_ops, multinomial, reduction
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/fft.py", line 14, in <module>
    from .opt import register_opt, op_lifter, register_opt2
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/opt.py", line 57, in <module>
    from .blocksparse import (GpuSparseBlockGemv, GpuSparseBlockOuter,
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blocksparse.py", line 91, in <module>
    gpu_sparse_block_gemv = GpuSparseBlockGemv(False)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blocksparse.py", line 31, in __init__
    COp.__init__(self, "blockgemv.c", "APPLY_SPECIFIC(blockgemv)")
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 1277, in __init__
    self.load_c_code(func_files)
  File "/search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 1357, in load_c_code
    "%s" % func_files[i])
ValueError: No valid section marker was found in file /search/odin/chengshanbo/anaconda2/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gpuarray/blockgemv.c
```

**Comment by nouiz** [comment] 2017-02-14 20:33
This was fixed today in Theano. The problem is that some Theano files had their end of lines changed from unix stile to windows stile.

Update Theano to the dev version and that error will be fixed.

**Closed by nouiz** 2017-02-14 20:33 UTC
